# Generated by Django 3.0.5 on 2020-04-06 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=50)),
                ('car_brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='antz.CarBrand')),
            ],
            options={
                'unique_together': {('name', 'car_brand')},
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='N/A', max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarTrim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=50, unique=True)),
                ('car_brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='antz.CarBrand')),
                ('car_model', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='antz.CarModel')),
            ],
            options={
                'unique_together': {('name', 'car_brand', 'car_model')},
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('kilometer', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antz.CarBrand')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antz.CarModel')),
                ('car_trim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='antz.CarTrim')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antz.URL')),
            ],
        ),
    ]
